
server:
   servlet:
      context-path: /movie

spring:
  datasource:
    url: jdbc:mysql://34.134.208.114:3306/movie?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: asd123
    driver-class-name: com.mysql.cj.jdbc.Driver